'use strict';
const halloweenWords=[
['pumpkin','An orange vegetable we carve.'],['cobweb','A spider’s web.'],['candle','Wax with a flame.'],['skeleton','The bones inside a body.'],['bat','An animal that flies at night.'],['ghost','A spirit in a haunted house.'],['broomstick','A witch can fly on this.'],['graveyard','A place with graves and gravestones.'],
['witch','A person who makes potions and casts spells.'],['vampire','A creature with fangs that drinks blood.'],['potion','A magical liquid.'],['spell','Magic words.'],['treat','A sweet or small gift.'],['costume','Clothes you wear to look like someone else.'],['scary','Something that makes you feel afraid.'],['haunted','A place where ghosts live.']
];
function art(index){const e=document.createElement('span');e.className='word-art';e.style.backgroundPosition=((index%4)*100/3)+'% '+(Math.floor(index/4)*100/3)+'%';e.setAttribute('aria-hidden','true');return e;}
function shuffled(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
const matchState={word:{round:0,selected:null},meaning:{round:0,selected:null}};
for(const mode of ['word','meaning']){
 const rounds=$('#'+mode+'-rounds');[0,1].forEach(round=>{const b=document.createElement('button');b.textContent=round===0?'Stage 1 · Decorations':'Stage 2 · Magic & mystery';b.onclick=()=>{matchState[mode]={round,selected:null};renderMatch(mode);};rounds.append(b);});renderMatch(mode);
}
function renderMatch(mode){const current=matchState[mode],start=current.round*8,indices=Array.from({length:8},(_,i)=>start+i);const pics=$('#'+mode+'-pictures'),targets=$('#'+mode+'-targets'),feedback=$('#'+mode+'-feedback');pics.replaceChildren();targets.replaceChildren();[...$('#'+mode+'-rounds').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===current.round)));
 const id=i=>'match-'+mode+'-'+i;const count=()=>indices.filter(i=>state.done.includes(id(i))).length;feedback.textContent=count()+' / 8 pairs';
 indices.forEach(i=>{const b=document.createElement('button');b.className='picture-card';b.dataset.index=i;b.setAttribute('aria-label',halloweenWords[i][0]+' picture');b.disabled=state.done.includes(id(i));if(b.disabled)b.classList.add('matched');b.append(art(i));b.onclick=()=>{current.selected=i;[...pics.children].forEach(x=>{const selected=Number(x.dataset.index)===i;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',String(selected));});feedback.textContent=mode==='word'?'Now choose the English name.':'Now choose the description.';};pics.append(b);});
 shuffled(indices).forEach(i=>{const b=document.createElement('button');b.className='match-target';b.textContent=halloweenWords[i][mode==='word'?0:1];b.disabled=state.done.includes(id(i));if(b.disabled)b.classList.add('matched');b.onclick=()=>{if(current.selected===null){feedback.textContent='Choose a picture first.';return;}if(current.selected===i){complete(id(i));const picture=[...pics.children].find(x=>Number(x.dataset.index)===i);picture.disabled=true;picture.classList.remove('selected');picture.classList.add('matched');picture.setAttribute('aria-pressed','false');b.disabled=true;b.classList.add('matched');current.selected=null;feedback.textContent=count()===8?'✓ All eight pairs found! Try the other stage.':'✓ '+halloweenWords[i][0]+' · '+count()+' / 8 pairs';}else{feedback.textContent='Not a match. Look at the picture again.';b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),500);}};targets.append(b);});}
const huntIndices=[0,1,2,3,4,5];shuffled([...huntIndices,'football','umbrella','frying pan']).forEach(i=>{const b=document.createElement('button');b.className='hunt-card';const label=document.createElement('span');label.textContent=typeof i==='number'?halloweenWords[i][0]:i;if(typeof i==='number'){b.append(art(i));b.disabled=state.done.includes('hunt-'+i);if(b.disabled)b.classList.add('matched');}else{const icon=document.createElement('span');icon.className='decoy-icon';icon.textContent={'football':'⚽','umbrella':'☂','frying pan':'🍳'}[i];b.append(icon);}b.append(label);b.onclick=()=>{if(typeof i==='number'){complete('hunt-'+i);b.disabled=true;b.classList.add('matched');const n=huntIndices.filter(x=>state.done.includes('hunt-'+x)).length;$('#hunt-feedback').textContent=n===6?'✓ Perfect. Mystic Falls is ready for Halloween!':n+' / 6 decorations';}else $('#hunt-feedback').textContent='A '+i+' is not very spooky. Try again.';};$('#decoration-hunt').append(b);});$('#hunt-feedback').textContent=huntIndices.filter(x=>state.done.includes('hunt-'+x)).length+' / 6 decorations';
const decorMissions=[
{item:1,zone:'above-door',sentence:'Put a cobweb above the door.',result:'There is a cobweb above the door.'},
{item:0,zone:'next-door',sentence:'Put a pumpkin next to the door.',result:'There is a pumpkin next to the door.'},
{item:4,zone:'above-house',sentence:'Put a bat above the house.',result:'There is a bat above the house.'},
{item:3,zone:'front-house',sentence:'Put a skeleton in front of the house.',result:'There is a skeleton in front of the house.'},
{item:5,zone:'behind-house',sentence:'Put a ghost behind the house.',result:'There is a ghost behind the house.'},
{item:2,zone:'window',sentence:'Put a candle in the window.',result:'There is a candle in the window.'}
];
const zones=[['above-door',56,47,'Above the door'],['next-door',65,71,'Next to the door'],['above-house',49,8,'Above the house'],['front-house',42,84,'In front of the house'],['behind-house',23,61,'Behind the house'],['window',71,56,'In the window']];let selectedItem=null;const scene=$('#decoration-scene');
zones.forEach(([id,x,y,label])=>{const b=document.createElement('button');b.className='drop-spot';b.dataset.zone=id;b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label',label);const sign=document.createElement('span');sign.className='spot-sign';sign.textContent='+';b.append(sign);const tip=document.createElement('span');tip.className='spot-tip';tip.textContent=label;b.append(tip);b.onclick=()=>tryPlace(selectedItem,id);b.ondragover=e=>{e.preventDefault();b.classList.add('drag-over');};b.ondragleave=()=>b.classList.remove('drag-over');b.ondrop=e=>{e.preventDefault();b.classList.remove('drag-over');const raw=e.dataTransfer.getData('text/plain');tryPlace(/^\d+$/.test(raw)?Number(raw):null,id);};scene.append(b);});
shuffled([0,1,2,3,4,5]).forEach(i=>{const b=document.createElement('button');b.className='tray-item';b.dataset.item=i;b.draggable=true;b.setAttribute('aria-label','Choose '+halloweenWords[i][0]);b.append(art(i));const label=document.createElement('span');label.textContent=halloweenWords[i][0];b.append(label);b.onclick=()=>{selectedItem=i;$$('.tray-item').forEach(x=>{const on=Number(x.dataset.item)===i;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',String(on));});$('#decor-feedback').textContent='Selected: '+halloweenWords[i][0]+'. Now choose its place.';};b.ondragstart=e=>{selectedItem=i;e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move';};$('#item-tray').append(b);});
function currentDecor(){return decorMissions.findIndex((_,i)=>!state.done.includes('decor-v3-'+i));}
function tryPlace(item,zone){const index=currentDecor();if(index<0)return;const mission=decorMissions[index];if(item===null){$('#decor-feedback').textContent='Choose an item first.';return;}if(item!==mission.item){$('#decor-feedback').textContent='The sentence asks for a '+halloweenWords[mission.item][0]+'. Choose that item.';return;}if(zone!==mission.zone){$('#decor-feedback').textContent='Right item, different place. '+mission.sentence;return;}complete('decor-v3-'+index);selectedItem=null;renderDecor();$('#decor-feedback').textContent='✓ '+mission.result+(currentDecor()<0?' The manor is ready for Halloween!':' Read your next mission.');}
function renderDecor(){let done=0;zones.forEach(([zone])=>{const b=$$('.drop-spot').find(x=>x.dataset.zone===zone),i=decorMissions.findIndex(x=>x.zone===zone),matched=state.done.includes('decor-v3-'+i);b.classList.toggle('filled',matched);b.disabled=matched;const old=b.querySelector('.word-art');if(old)old.remove();if(matched){b.append(art(decorMissions[i].item));done++;}});$$('.tray-item').forEach(b=>{const placed=decorMissions.some((m,i)=>m.item===Number(b.dataset.item)&&state.done.includes('decor-v3-'+i));b.disabled=placed;b.draggable=!placed;b.classList.toggle('matched',placed);b.classList.remove('selected');b.setAttribute('aria-pressed','false');});const index=currentDecor();$('#decor-count').textContent=done+' / 6 decorations';$('#decor-sentence').textContent=index<0?'The manor is ready. There are six Halloween decorations!':decorMissions[index].sentence;$('#replay-decor').hidden=index>=0;}
$('#replay-decor').onclick=()=>{state.done=state.done.filter(x=>!x.startsWith('decor-v3-'));selectedItem=null;save();renderDecor();$('#decor-feedback').textContent='A fresh night! Read the sentence and choose an item.';};renderDecor();
const facts=[
['Pumpkins weren’t the first lanterns!','People in Ireland and Scotland carved scary faces into turnips. Imagine carving that tiny vegetable!','https://www.history.com/articles/history-of-the-jack-o-lantern-irish-origins','HISTORY'],
['A sweet called “Chicken Feed”','Candy corn was once sold as “Chicken Feed”. Luckily, you don’t have to be a chicken to enjoy it!','https://www.smithsonianmag.com/smart-news/candy-corn-hasnt-changed-19th-century-180957107/','Smithsonian'],
['Meet Jack of the Lantern','The name jack-o’-lantern is linked to an Irish story about Stingy Jack, who wandered with a light in a turnip.','https://www.history.com/articles/history-of-the-jack-o-lantern-irish-origins','HISTORY']
];let factIndex=0;function showFact(){const [title,body,url,source]=facts[factIndex];const root=$('#fun-facts');root.replaceChildren();const h=document.createElement('h4');h.textContent=title;const p=document.createElement('p');p.textContent=body;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.className='fact-source';a.textContent='Source: '+source;root.append(h,p,a);}$('#next-fact').onclick=()=>{factIndex=(factIndex+1)%facts.length;showFact();};showFact();
// Restore the original candy selection and immediate speaking challenge in Decorate.
const oldChallenges=['Name 4 Halloween decorations.','Make a sentence with “There are…”.','TRICK! Say “three creepy creatures” three times fast.','What costume would you wear? Why?','Make one rule with MUSTN’T.'];const candyRoot=$('#treat0');candyRoot.replaceChildren();const heading=document.createElement('div');heading.innerHTML='<div class="label">FINAL ROUND</div><h3>Trick or Treat?</h3><p>Pick a treat. Every candy hides a speaking challenge.</p>';const candyRow=document.createElement('div');candyRow.className='candies';const challenge=document.createElement('p');challenge.className='challenge';challenge.textContent='Pick one.';challenge.setAttribute('aria-live','polite');['🍬','🍭','🍫','🧁','🍪'].forEach((c,i)=>{const b=document.createElement('button');b.textContent=c;b.setAttribute('aria-label',['Candy','Lollipop','Chocolate','Cupcake','Cookie'][i]);b.onclick=()=>challenge.textContent=oldChallenges[i];candyRow.append(b);});candyRoot.append(heading,candyRow,challenge);
tasks[0]=[...['word','meaning'].flatMap(mode=>halloweenWords.map((_,i)=>'match-'+mode+'-'+i)),...huntIndices.map(i=>'hunt-'+i),...decorMissions.map((_,i)=>'decor-v3-'+i),'t0','t1','t2'];update();
