'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='mystic-falls-v2';let state={done:[],clues:[],alibis:[],ingredients:[],step:0,place:0,tab:0,treats:[]};try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.done)&&Array.isArray(saved.clues)&&Array.isArray(saved.alibis)&&Array.isArray(saved.ingredients)&&Array.isArray(saved.treats))state={...state,...saved};}catch{}
const tasks=[['v0','v1','v2','v3','v4','v5','v6','v7','place0','place1','place2','place3','d0','d1','d2','t0','t1','t2'],['r0','r1','r2','r3','r4','ingredients','spell'],['p0','p1','p2','case']];
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}update();}
function complete(id){if(!state.done.includes(id))state.done.push(id);save();}
function update(){const n=state.done.length+state.treats.length;$('#total').textContent=n+' treats collected';$('#mission-progress').textContent=tasks[state.tab].filter(x=>state.done.includes(x)).length+' / '+tasks[state.tab].length+' mission tasks complete';const ready=state.alibis.length===4&&state.clues.length===5&&['p0','p1','p2'].every(x=>state.done.includes(x));$('#submit-case').disabled=!ready;$('#case-gate').textContent=ready?'Your evidence is ready. Explain your conclusion.':`Read alibis (${state.alibis.length}/4), inspect clues (${state.clues.length}/5) and complete Detective English before accusing anyone.`;}
function tab(i,focus=false){state.tab=i;$$('[role=tab]').forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;if(i===j&&focus)b.focus();});$$('[role=tabpanel]').forEach((p,j)=>p.hidden=i!==j);save();}
$$('[data-tab]').forEach((b,i)=>{b.onclick=()=>tab(i);b.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();tab(e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3,true);}};});$('#help').onclick=()=>{$('#notebook').hidden=!$('#notebook').hidden;$('#help').setAttribute('aria-expanded',String(!$('#notebook').hidden));};$('#reset').onclick=()=>{if(confirm('Restart all three missions and clear collected treats?')){try{localStorage.removeItem(KEY);}catch{}location.reload();}};
function quiz(container,id,prompt,options,answer,explanation){const box=document.createElement('div');box.className='quiz';const p=document.createElement('p');p.textContent=prompt;box.append(p);const row=document.createElement('div');row.className='choices';const feedback=document.createElement('p');feedback.className='feedback';feedback.setAttribute('aria-live','polite');options.forEach((text,i)=>{const b=document.createElement('button');b.textContent=text;row.append(b);if(state.done.includes(id)){b.disabled=true;if(i===answer)b.classList.add('good');feedback.textContent='✓ '+explanation;}b.onclick=()=>{if(i===answer){complete(id);b.classList.add('good');[...row.children].forEach(x=>x.disabled=true);feedback.textContent='✓ '+explanation;}else feedback.textContent='Try again. '+explanation.replace(/^.*? — /,'');};});box.append(row,feedback);$(container).append(box);}
const placements=[['Put a pumpkin next to the front door.','next to the door',['on the roof','next to the door','under the table'],1,58,66,'pumpkin'],['Put three candles on the porch table.','on the table',['on the table','under the table','above the tree'],0,25,80,'three candles'],['Put a cobweb above the front door.','above the door',['between the trees','above the door','inside the pumpkin'],1,58,40,'cobweb'],['Put two bats in the old tree.','in the tree',['on the table','under the door','in the tree'],2,10,38,'two bats']];
function renderGarden(){ $$('.placed').forEach(x=>x.remove());placements.forEach((x,i)=>{if(state.done.includes('place'+i)){const s=document.createElement('span');s.className='placed';s.style.left=x[4]+'%';s.style.top=x[5]+'%';s.textContent=x[6];$('#garden').append(s);}});}
function place(){renderGarden();const i=state.place;$('#places').replaceChildren();if(i>=4){$('#place-prompt').textContent='The house is ready. There is a pumpkin next to the door. There are three candles on the table.';$('#place-feedback').textContent='✓ All four decorations are in place.';return;}const x=placements[i];$('#place-prompt').textContent=x[0];x[2].forEach((t,j)=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{if(j===x[3]){state.place++;complete('place'+i);$('#place-feedback').textContent='✓ '+x[6]+' '+x[1]+'.';place();}else $('#place-feedback').textContent='Read the instruction again: '+x[0];};$('#places').append(b);});}
quiz('#describe','d0','___ a pumpkin next to the door.',['There is','There are'],0,'There is a pumpkin — one object.');quiz('#describe','d1','___ three candles on the table.',['There is','There are'],1,'There are three candles — more than one.');quiz('#describe','d2','The cobweb is ___ the door.',['under','above','between'],1,'The cobweb is above the door.');
quiz('#traditions','t0','To make a jack-o’-lantern, we ___ a face into a pumpkin.',['carve','boil','wrap'],0,'We carve a face and put a light inside.');quiz('#traditions','t1','Children wear costumes and say ___ at the door.',['Happy birthday!','Trick or treat!','Good morning!'],1,'Trick or treat! They ask for sweets.');quiz('#traditions','t2','A treat is ___.',['a sweet or small gift','a scary threat','a witch’s rule'],0,'A treat is a sweet or a small gift.');
const rules=[['The potion is poisonous. You ___ drink it.',['must','mustn’t','don’t have to'],1,'mustn’t — it is forbidden.'],['Bonnie’s school requires a safety crystal. Students ___ bring one.',['have to','mustn’t','don’t have to'],0,'have to — the school requires it.'],['Costumes are optional. You ___ wear one.',['mustn’t','have to','don’t have to'],2,'don’t have to — you can, but it is optional.'],['Bonnie gives a strong rule: “You ___ keep the candles away from cobwebs.”',['must','mustn’t','don’t have to'],0,'must — keep the candles away from cobwebs.'],['Which sentence is correct?',['She have to bring herbs.','She has to bring herbs.','She must to bring herbs.'],1,'She has to bring herbs. After must, use the verb without to.']];rules.forEach((x,i)=>quiz('#rules','r'+i,...x));
function spell(){ $('#spell').replaceChildren();[1,0,2].forEach(i=>{const b=document.createElement('button');b.textContent=['Put the herbs in the cauldron','Light three candles','Say “Protect this house”'][i];b.disabled=i<state.step;if(b.disabled)b.classList.add('good');b.onclick=()=>{if(i===state.step){state.step++;if(state.step===3)complete('spell');else save();$('#spell-feedback').textContent=state.step===3?'✓ The protection spell worked. Bonnie approves.':'Correct. Follow the next recipe step.';spell();}else $('#spell-feedback').textContent='The spell fizzled. Check “First / Then / Finally” in the recipe.';};$('#spell').append(b);});if(state.step===3)$('#spell-feedback').textContent='✓ The protection spell worked.';}
['herbs','candles','crystal','pumpkin','treat','cobweb'].forEach((x,i)=>{const b=document.createElement('button');b.textContent=x;if(state.ingredients.includes(x)){b.disabled=true;b.classList.add('good');}b.onclick=()=>{if(i<3){state.ingredients.push(x);b.disabled=true;b.classList.add('good');if(state.ingredients.length===3)complete('ingredients');else save();$('#ingredient-feedback').textContent=state.ingredients.length+' / 3 ingredients ready';}else $('#ingredient-feedback').textContent=x+' is Halloween vocabulary, but it is not in Bonnie’s recipe.';};$('#ingredients').append(b);});$('#ingredient-feedback').textContent=state.ingredients.length+' / 3 ingredients ready';
const people=[['Damon','I stayed in the kitchen from 11:40 to 11:50. Elena filmed our trick-or-treat tasting.','I ate a caramel treat. I didn’t enter the conservatory.'],['Stefan','I stayed in the library from 11:40 to 11:50. I didn’t enter the conservatory.','I borrowed a book about banishing ghosts at 11:30. The ghost threatened to reveal my secret.'],['Bonnie','I taught a protection spell in the academy from 11:40 to 11:50.','I used white candles. I didn’t use the black candle.'],['Caroline','I stayed in the kitchen with Damon from 11:40 to 11:50.','I gave Elena a treat and fixed a cobweb above the kitchen door.']];
people.forEach((person,i)=>{const b=document.createElement('button');b.textContent=person[0];$('#suspects').append(b);b.onclick=()=>{const area=$('#interview');area.replaceChildren();const h=document.createElement('h3');h.textContent=person[0];area.append(h);['Where were you at 11:47?','What did you do that night?'].forEach((q,j)=>{const ask=document.createElement('button');ask.className='primary';ask.textContent=q;ask.style.margin='5px';area.append(ask);ask.onclick=()=>{let quote=area.querySelector('blockquote');if(!quote){quote=document.createElement('blockquote');area.append(quote);}quote.textContent=person[j+1];if(j===0&&!state.alibis.includes(i)){state.alibis.push(i);save();}};});};});
const clues=[['The ghost’s last message','The ghost’s enchanted watch stopped at 11:47. It recorded: “A living person lit a black candle here and said the banishing spell.” The spell destroyed the ghost instantly.'],['The kitchen recording','Elena’s continuous video shows Damon and Caroline in the kitchen from 11:40 to 11:50, including 11:47. Neither left.'],['The academy recording','A continuous academy video shows Bonnie teaching from 11:40 to 11:50. At 11:47, she lit three white candles in front of her students.'],['The conservatory door record','The only entrance recorded Stefan entering at 11:44 and leaving at 11:49. Nobody else entered between 11:40 and 11:50. The windows were sealed.'],['The black candle','A freshly burned black candle and the open banishing book lay on the conservatory table. The library loan record says Stefan borrowed that book at 11:30.']];
clues.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x[0];$('#clues').append(b);b.onclick=()=>{if(!state.clues.includes(i)){state.clues.push(i);save();}renderClues();};});function renderClues(){$('#evidence-log').replaceChildren();state.clues.forEach(i=>{const p=document.createElement('div');p.className='evidence';const b=document.createElement('b');b.textContent=clues[i][0];const text=document.createElement('p');text.textContent=clues[i][1];p.append(b,text);$('#evidence-log').append(p);});}
quiz('#past','p0','Choose a correct interrogation question.',['Where did you were?','Where were you at 11:47?','Where you were at 11:47?'],1,'Where were you at 11:47? Use were without did.');quiz('#past','p1','___ the black candle?',['Did you light','Did you lit','Were you light'],0,'Did you light the black candle? After did, use the base verb.');quiz('#past','p2','Complete the report: Stefan ___ the book, but he ___ the truth.',['borrow / didn’t told','borrowed / didn’t tell','borrowed / doesn’t told'],1,'Stefan borrowed the book, but he didn’t tell the truth.');
$('#accusation').onsubmit=e=>{e.preventDefault();if($('#submit-case').disabled)return;const correct=$('#killer').value==='Stefan'&&$('#method').value==='candle'&&$('#proof').value==='door';if(correct){complete('case');$('#verdict').textContent='CASE CLOSED. Stefan entered at 11:44 and left at 11:49: he was inside at 11:47. His library alibi was false. Damon and Caroline were continuously filmed in the kitchen; Bonnie was filmed in the academy. Stefan lit the black candle and said the spell. The book explains his method and his statement supplies a motive. Say: “Stefan destroyed the ghost because…”';}else $('#verdict').textContent='Your case has a contradiction. Compare the exact time, continuous recordings, door record and the required method. Try again.';};if(state.done.includes('case'))$('#verdict').textContent='✓ Case solved: Stefan lit the black candle at 11:47. The door record disproved his library alibi.';
const challenges=[['TREAT: Describe the decorated house using there is and there are.','TRICK: Say “three spooky treats” three times.','TREAT: Explain how to carve a jack-o’-lantern.'],['TREAT: Give Bonnie a rule with must and a rule with mustn’t.','TRICK: Act out a witch, then name the cauldron, candle and spell.','TREAT: Tell Damon what he has to do before the party.'],['TREAT: Retell the crime using entered, lit, said and left.','TRICK: Ask two questions beginning with Did you…?','TREAT: Explain why the other three suspects had alibis.']];challenges.forEach((list,chapter)=>{const root=$('#treat'+chapter);root.innerHTML='<div><div class="label">THE DOOR IS OPEN</div><h3>Trick or Treat?</h3><small>Pick a door. Say your answer aloud, then collect your treat.</small></div>';const msg=document.createElement('p');msg.className='challenge';msg.setAttribute('aria-live','polite');const collect=document.createElement('button');collect.textContent='I said it — collect treat';collect.hidden=true;list.forEach((text,i)=>{const id=chapter+'-'+i;const b=document.createElement('button');b.textContent='Door '+(i+1)+(state.treats.includes(id)?' ✓':'');b.onclick=()=>{msg.textContent=text;collect.hidden=state.treats.includes(id);collect.onclick=()=>{if(!state.treats.includes(id))state.treats.push(id);b.textContent='Door '+(i+1)+' ✓';collect.hidden=true;save();msg.textContent='✓ Treat collected. '+text;};};root.append(b);});root.append(msg,collect);});

const vocabulary=[['pumpkin','An orange vegetable we carve'],['cobweb','A spider’s web'],['candle','Wax with a flame'],['bat','An animal that flies at night'],['ghost','A spirit in a haunted house'],['cauldron','A large pot for a witch’s potion'],['spell','Magic words'],['treat','A sweet or small gift']];let selectedWord=null;
vocabulary.forEach((pair,i)=>{const b=document.createElement('button');b.textContent=pair[0];b.onclick=()=>{selectedWord=i;$('#vocab-feedback').textContent='Match: '+pair[0];};b.disabled=state.done.includes('v'+i);$('#vocab-words').append(b);});[3,6,0,7,1,5,2,4].forEach(i=>{const b=document.createElement('button');b.textContent=vocabulary[i][1];b.disabled=state.done.includes('v'+i);b.onclick=()=>{if(selectedWord===null){$('#vocab-feedback').textContent='Choose an English word first.';return;}if(selectedWord===i){complete('v'+i);b.disabled=true;$('#vocab-words').children[i].disabled=true;selectedWord=null;$('#vocab-feedback').textContent='✓ '+vocabulary[i][0]+' · '+vocabulary.filter((_,j)=>state.done.includes('v'+j)).length+' / 8 pairs';}else $('#vocab-feedback').textContent='Not a match. Try another meaning.';};$('#vocab-meanings').append(b);});

place();spell();renderClues();tab(Math.min(2,Math.max(0,state.tab)));update();
